#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RushDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="matchit")]
	public partial class AbDALDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbAntibodyMethod(tbAntibodyMethod instance);
    partial void UpdatetbAntibodyMethod(tbAntibodyMethod instance);
    partial void DeletetbAntibodyMethod(tbAntibodyMethod instance);
    #endregion
		
		public AbDALDataContext() : 
				base(global::RushDAL.Properties.Settings.Default.matchitConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AbDALDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbDALDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbDALDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbDALDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbAntibodyMethod> tbAntibodyMethods
		{
			get
			{
				return this.GetTable<tbAntibodyMethod>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSampleForLoad")]
		public ISingleResult<GetSampleForLoadResult> GetSampleForLoad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string batchID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string sampleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), batchID, sampleID);
			return ((ISingleResult<GetSampleForLoadResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbAntibodyMethod")]
	public partial class tbAntibodyMethod : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AntibodyID;
		
		private string _lotID;
		
		private string _sessionID;
		
		private string _sampleID;
		
		private System.Nullable<int> _logicID;
		
		private string _wellLocation;
		
		private System.Nullable<decimal> _raw;
		
		private System.Nullable<decimal> _rVal;
		
		private System.Nullable<int> _pctPositive;
		
		private System.Nullable<int> _assignCutoff;
		
		private System.Nullable<decimal> _assignAdjust1;
		
		private System.Nullable<decimal> _assignAdjust2;
		
		private System.Nullable<decimal> _assignAdjust3;
		
		private System.Nullable<int> _tail;
		
		private System.Nullable<System.DateTime> _runDate;
		
		private string _comments;
		
		private System.Nullable<int> _includeweak;
		
		private System.Nullable<int> _reviewer;
		
		private System.Nullable<System.DateTime> _reviewerDt;
		
		private System.Nullable<System.DateTime> _createdt;
		
		private System.Nullable<System.DateTime> _updatedt;
		
		private System.Nullable<int> _updateby;
		
		private System.Nullable<int> _manualAssignFlg;
		
		private int _ctrlSampleFailed;
		
		private int _lockedFlg;
		
		private int _approved;
		
		private int _useVBAF;
		
		private System.Nullable<bool> _negativeCtrl;
		
		private System.Nullable<decimal> _pra;
		
		private System.Nullable<decimal> _virtualPra;
		
		private int _CalcUsed;
		
		private int _completed;
		
		private System.Nullable<int> _completedBy;
		
		private System.Nullable<int> _approvedBy;
		
		private string _maskedAntigens;
		
		private System.Nullable<System.DateTime> _ApprovedDt;
		
		private System.Nullable<System.DateTime> _CompletedDt;
		
		private bool _useMFICutoff;
		
		private System.Nullable<decimal> _MFICutoffValue;
		
		private System.Nullable<int> _ID4DigitLogicID;
		
		private System.Nullable<decimal> _adjAltCalc1;
		
		private System.Nullable<decimal> _adjAltCalc2;
		
		private System.Nullable<int> _TailLogicID;
		
		private System.Nullable<int> _excludeweak;
		
		private System.Nullable<int> _Version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAntibodyIDChanging(int value);
    partial void OnAntibodyIDChanged();
    partial void OnlotIDChanging(string value);
    partial void OnlotIDChanged();
    partial void OnsessionIDChanging(string value);
    partial void OnsessionIDChanged();
    partial void OnsampleIDChanging(string value);
    partial void OnsampleIDChanged();
    partial void OnlogicIDChanging(System.Nullable<int> value);
    partial void OnlogicIDChanged();
    partial void OnwellLocationChanging(string value);
    partial void OnwellLocationChanged();
    partial void OnrawChanging(System.Nullable<decimal> value);
    partial void OnrawChanged();
    partial void OnrValChanging(System.Nullable<decimal> value);
    partial void OnrValChanged();
    partial void OnpctPositiveChanging(System.Nullable<int> value);
    partial void OnpctPositiveChanged();
    partial void OnassignCutoffChanging(System.Nullable<int> value);
    partial void OnassignCutoffChanged();
    partial void OnassignAdjust1Changing(System.Nullable<decimal> value);
    partial void OnassignAdjust1Changed();
    partial void OnassignAdjust2Changing(System.Nullable<decimal> value);
    partial void OnassignAdjust2Changed();
    partial void OnassignAdjust3Changing(System.Nullable<decimal> value);
    partial void OnassignAdjust3Changed();
    partial void OntailChanging(System.Nullable<int> value);
    partial void OntailChanged();
    partial void OnrunDateChanging(System.Nullable<System.DateTime> value);
    partial void OnrunDateChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnincludeweakChanging(System.Nullable<int> value);
    partial void OnincludeweakChanged();
    partial void OnreviewerChanging(System.Nullable<int> value);
    partial void OnreviewerChanged();
    partial void OnreviewerDtChanging(System.Nullable<System.DateTime> value);
    partial void OnreviewerDtChanged();
    partial void OncreatedtChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedtChanged();
    partial void OnupdatedtChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedtChanged();
    partial void OnupdatebyChanging(System.Nullable<int> value);
    partial void OnupdatebyChanged();
    partial void OnmanualAssignFlgChanging(System.Nullable<int> value);
    partial void OnmanualAssignFlgChanged();
    partial void OnctrlSampleFailedChanging(int value);
    partial void OnctrlSampleFailedChanged();
    partial void OnlockedFlgChanging(int value);
    partial void OnlockedFlgChanged();
    partial void OnapprovedChanging(int value);
    partial void OnapprovedChanged();
    partial void OnuseVBAFChanging(int value);
    partial void OnuseVBAFChanged();
    partial void OnnegativeCtrlChanging(System.Nullable<bool> value);
    partial void OnnegativeCtrlChanged();
    partial void OnpraChanging(System.Nullable<decimal> value);
    partial void OnpraChanged();
    partial void OnvirtualPraChanging(System.Nullable<decimal> value);
    partial void OnvirtualPraChanged();
    partial void OnCalcUsedChanging(int value);
    partial void OnCalcUsedChanged();
    partial void OncompletedChanging(int value);
    partial void OncompletedChanged();
    partial void OncompletedByChanging(System.Nullable<int> value);
    partial void OncompletedByChanged();
    partial void OnapprovedByChanging(System.Nullable<int> value);
    partial void OnapprovedByChanged();
    partial void OnmaskedAntigensChanging(string value);
    partial void OnmaskedAntigensChanged();
    partial void OnApprovedDtChanging(System.Nullable<System.DateTime> value);
    partial void OnApprovedDtChanged();
    partial void OnCompletedDtChanging(System.Nullable<System.DateTime> value);
    partial void OnCompletedDtChanged();
    partial void OnuseMFICutoffChanging(bool value);
    partial void OnuseMFICutoffChanged();
    partial void OnMFICutoffValueChanging(System.Nullable<decimal> value);
    partial void OnMFICutoffValueChanged();
    partial void OnID4DigitLogicIDChanging(System.Nullable<int> value);
    partial void OnID4DigitLogicIDChanged();
    partial void OnadjAltCalc1Changing(System.Nullable<decimal> value);
    partial void OnadjAltCalc1Changed();
    partial void OnadjAltCalc2Changing(System.Nullable<decimal> value);
    partial void OnadjAltCalc2Changed();
    partial void OnTailLogicIDChanging(System.Nullable<int> value);
    partial void OnTailLogicIDChanged();
    partial void OnexcludeweakChanging(System.Nullable<int> value);
    partial void OnexcludeweakChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    #endregion
		
		public tbAntibodyMethod()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntibodyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AntibodyID
		{
			get
			{
				return this._AntibodyID;
			}
			set
			{
				if ((this._AntibodyID != value))
				{
					this.OnAntibodyIDChanging(value);
					this.SendPropertyChanging();
					this._AntibodyID = value;
					this.SendPropertyChanged("AntibodyID");
					this.OnAntibodyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lotID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string lotID
		{
			get
			{
				return this._lotID;
			}
			set
			{
				if ((this._lotID != value))
				{
					this.OnlotIDChanging(value);
					this.SendPropertyChanging();
					this._lotID = value;
					this.SendPropertyChanged("lotID");
					this.OnlotIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sessionID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sessionID
		{
			get
			{
				return this._sessionID;
			}
			set
			{
				if ((this._sessionID != value))
				{
					this.OnsessionIDChanging(value);
					this.SendPropertyChanging();
					this._sessionID = value;
					this.SendPropertyChanged("sessionID");
					this.OnsessionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sampleID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sampleID
		{
			get
			{
				return this._sampleID;
			}
			set
			{
				if ((this._sampleID != value))
				{
					this.OnsampleIDChanging(value);
					this.SendPropertyChanging();
					this._sampleID = value;
					this.SendPropertyChanged("sampleID");
					this.OnsampleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logicID", DbType="Int")]
		public System.Nullable<int> logicID
		{
			get
			{
				return this._logicID;
			}
			set
			{
				if ((this._logicID != value))
				{
					this.OnlogicIDChanging(value);
					this.SendPropertyChanging();
					this._logicID = value;
					this.SendPropertyChanged("logicID");
					this.OnlogicIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wellLocation", DbType="VarChar(15)")]
		public string wellLocation
		{
			get
			{
				return this._wellLocation;
			}
			set
			{
				if ((this._wellLocation != value))
				{
					this.OnwellLocationChanging(value);
					this.SendPropertyChanging();
					this._wellLocation = value;
					this.SendPropertyChanged("wellLocation");
					this.OnwellLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raw", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> raw
		{
			get
			{
				return this._raw;
			}
			set
			{
				if ((this._raw != value))
				{
					this.OnrawChanging(value);
					this.SendPropertyChanging();
					this._raw = value;
					this.SendPropertyChanged("raw");
					this.OnrawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rVal", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> rVal
		{
			get
			{
				return this._rVal;
			}
			set
			{
				if ((this._rVal != value))
				{
					this.OnrValChanging(value);
					this.SendPropertyChanging();
					this._rVal = value;
					this.SendPropertyChanged("rVal");
					this.OnrValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pctPositive", DbType="Int")]
		public System.Nullable<int> pctPositive
		{
			get
			{
				return this._pctPositive;
			}
			set
			{
				if ((this._pctPositive != value))
				{
					this.OnpctPositiveChanging(value);
					this.SendPropertyChanging();
					this._pctPositive = value;
					this.SendPropertyChanged("pctPositive");
					this.OnpctPositiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignCutoff", DbType="Int")]
		public System.Nullable<int> assignCutoff
		{
			get
			{
				return this._assignCutoff;
			}
			set
			{
				if ((this._assignCutoff != value))
				{
					this.OnassignCutoffChanging(value);
					this.SendPropertyChanging();
					this._assignCutoff = value;
					this.SendPropertyChanged("assignCutoff");
					this.OnassignCutoffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignAdjust1", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> assignAdjust1
		{
			get
			{
				return this._assignAdjust1;
			}
			set
			{
				if ((this._assignAdjust1 != value))
				{
					this.OnassignAdjust1Changing(value);
					this.SendPropertyChanging();
					this._assignAdjust1 = value;
					this.SendPropertyChanged("assignAdjust1");
					this.OnassignAdjust1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignAdjust2", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> assignAdjust2
		{
			get
			{
				return this._assignAdjust2;
			}
			set
			{
				if ((this._assignAdjust2 != value))
				{
					this.OnassignAdjust2Changing(value);
					this.SendPropertyChanging();
					this._assignAdjust2 = value;
					this.SendPropertyChanged("assignAdjust2");
					this.OnassignAdjust2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignAdjust3", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> assignAdjust3
		{
			get
			{
				return this._assignAdjust3;
			}
			set
			{
				if ((this._assignAdjust3 != value))
				{
					this.OnassignAdjust3Changing(value);
					this.SendPropertyChanging();
					this._assignAdjust3 = value;
					this.SendPropertyChanged("assignAdjust3");
					this.OnassignAdjust3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tail", DbType="Int")]
		public System.Nullable<int> tail
		{
			get
			{
				return this._tail;
			}
			set
			{
				if ((this._tail != value))
				{
					this.OntailChanging(value);
					this.SendPropertyChanging();
					this._tail = value;
					this.SendPropertyChanged("tail");
					this.OntailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_runDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> runDate
		{
			get
			{
				return this._runDate;
			}
			set
			{
				if ((this._runDate != value))
				{
					this.OnrunDateChanging(value);
					this.SendPropertyChanging();
					this._runDate = value;
					this.SendPropertyChanged("runDate");
					this.OnrunDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(1024)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_includeweak", DbType="Int")]
		public System.Nullable<int> includeweak
		{
			get
			{
				return this._includeweak;
			}
			set
			{
				if ((this._includeweak != value))
				{
					this.OnincludeweakChanging(value);
					this.SendPropertyChanging();
					this._includeweak = value;
					this.SendPropertyChanged("includeweak");
					this.OnincludeweakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reviewer", DbType="Int")]
		public System.Nullable<int> reviewer
		{
			get
			{
				return this._reviewer;
			}
			set
			{
				if ((this._reviewer != value))
				{
					this.OnreviewerChanging(value);
					this.SendPropertyChanging();
					this._reviewer = value;
					this.SendPropertyChanged("reviewer");
					this.OnreviewerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reviewerDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> reviewerDt
		{
			get
			{
				return this._reviewerDt;
			}
			set
			{
				if ((this._reviewerDt != value))
				{
					this.OnreviewerDtChanging(value);
					this.SendPropertyChanging();
					this._reviewerDt = value;
					this.SendPropertyChanged("reviewerDt");
					this.OnreviewerDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedt", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedt
		{
			get
			{
				return this._updatedt;
			}
			set
			{
				if ((this._updatedt != value))
				{
					this.OnupdatedtChanging(value);
					this.SendPropertyChanging();
					this._updatedt = value;
					this.SendPropertyChanged("updatedt");
					this.OnupdatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateby", DbType="Int")]
		public System.Nullable<int> updateby
		{
			get
			{
				return this._updateby;
			}
			set
			{
				if ((this._updateby != value))
				{
					this.OnupdatebyChanging(value);
					this.SendPropertyChanging();
					this._updateby = value;
					this.SendPropertyChanged("updateby");
					this.OnupdatebyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manualAssignFlg", DbType="Int")]
		public System.Nullable<int> manualAssignFlg
		{
			get
			{
				return this._manualAssignFlg;
			}
			set
			{
				if ((this._manualAssignFlg != value))
				{
					this.OnmanualAssignFlgChanging(value);
					this.SendPropertyChanging();
					this._manualAssignFlg = value;
					this.SendPropertyChanged("manualAssignFlg");
					this.OnmanualAssignFlgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctrlSampleFailed", DbType="Int NOT NULL")]
		public int ctrlSampleFailed
		{
			get
			{
				return this._ctrlSampleFailed;
			}
			set
			{
				if ((this._ctrlSampleFailed != value))
				{
					this.OnctrlSampleFailedChanging(value);
					this.SendPropertyChanging();
					this._ctrlSampleFailed = value;
					this.SendPropertyChanged("ctrlSampleFailed");
					this.OnctrlSampleFailedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lockedFlg", DbType="Int NOT NULL")]
		public int lockedFlg
		{
			get
			{
				return this._lockedFlg;
			}
			set
			{
				if ((this._lockedFlg != value))
				{
					this.OnlockedFlgChanging(value);
					this.SendPropertyChanging();
					this._lockedFlg = value;
					this.SendPropertyChanged("lockedFlg");
					this.OnlockedFlgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approved", DbType="Int NOT NULL")]
		public int approved
		{
			get
			{
				return this._approved;
			}
			set
			{
				if ((this._approved != value))
				{
					this.OnapprovedChanging(value);
					this.SendPropertyChanging();
					this._approved = value;
					this.SendPropertyChanged("approved");
					this.OnapprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_useVBAF", DbType="Int NOT NULL")]
		public int useVBAF
		{
			get
			{
				return this._useVBAF;
			}
			set
			{
				if ((this._useVBAF != value))
				{
					this.OnuseVBAFChanging(value);
					this.SendPropertyChanging();
					this._useVBAF = value;
					this.SendPropertyChanged("useVBAF");
					this.OnuseVBAFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_negativeCtrl", DbType="Bit")]
		public System.Nullable<bool> negativeCtrl
		{
			get
			{
				return this._negativeCtrl;
			}
			set
			{
				if ((this._negativeCtrl != value))
				{
					this.OnnegativeCtrlChanging(value);
					this.SendPropertyChanging();
					this._negativeCtrl = value;
					this.SendPropertyChanged("negativeCtrl");
					this.OnnegativeCtrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pra", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> pra
		{
			get
			{
				return this._pra;
			}
			set
			{
				if ((this._pra != value))
				{
					this.OnpraChanging(value);
					this.SendPropertyChanging();
					this._pra = value;
					this.SendPropertyChanged("pra");
					this.OnpraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_virtualPra", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> virtualPra
		{
			get
			{
				return this._virtualPra;
			}
			set
			{
				if ((this._virtualPra != value))
				{
					this.OnvirtualPraChanging(value);
					this.SendPropertyChanging();
					this._virtualPra = value;
					this.SendPropertyChanged("virtualPra");
					this.OnvirtualPraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcUsed", DbType="Int NOT NULL")]
		public int CalcUsed
		{
			get
			{
				return this._CalcUsed;
			}
			set
			{
				if ((this._CalcUsed != value))
				{
					this.OnCalcUsedChanging(value);
					this.SendPropertyChanging();
					this._CalcUsed = value;
					this.SendPropertyChanged("CalcUsed");
					this.OnCalcUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completed", DbType="Int NOT NULL")]
		public int completed
		{
			get
			{
				return this._completed;
			}
			set
			{
				if ((this._completed != value))
				{
					this.OncompletedChanging(value);
					this.SendPropertyChanging();
					this._completed = value;
					this.SendPropertyChanged("completed");
					this.OncompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completedBy", DbType="Int")]
		public System.Nullable<int> completedBy
		{
			get
			{
				return this._completedBy;
			}
			set
			{
				if ((this._completedBy != value))
				{
					this.OncompletedByChanging(value);
					this.SendPropertyChanging();
					this._completedBy = value;
					this.SendPropertyChanged("completedBy");
					this.OncompletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approvedBy", DbType="Int")]
		public System.Nullable<int> approvedBy
		{
			get
			{
				return this._approvedBy;
			}
			set
			{
				if ((this._approvedBy != value))
				{
					this.OnapprovedByChanging(value);
					this.SendPropertyChanging();
					this._approvedBy = value;
					this.SendPropertyChanged("approvedBy");
					this.OnapprovedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maskedAntigens", DbType="VarChar(MAX)")]
		public string maskedAntigens
		{
			get
			{
				return this._maskedAntigens;
			}
			set
			{
				if ((this._maskedAntigens != value))
				{
					this.OnmaskedAntigensChanging(value);
					this.SendPropertyChanging();
					this._maskedAntigens = value;
					this.SendPropertyChanged("maskedAntigens");
					this.OnmaskedAntigensChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ApprovedDt
		{
			get
			{
				return this._ApprovedDt;
			}
			set
			{
				if ((this._ApprovedDt != value))
				{
					this.OnApprovedDtChanging(value);
					this.SendPropertyChanging();
					this._ApprovedDt = value;
					this.SendPropertyChanged("ApprovedDt");
					this.OnApprovedDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletedDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CompletedDt
		{
			get
			{
				return this._CompletedDt;
			}
			set
			{
				if ((this._CompletedDt != value))
				{
					this.OnCompletedDtChanging(value);
					this.SendPropertyChanging();
					this._CompletedDt = value;
					this.SendPropertyChanged("CompletedDt");
					this.OnCompletedDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_useMFICutoff", DbType="Bit NOT NULL")]
		public bool useMFICutoff
		{
			get
			{
				return this._useMFICutoff;
			}
			set
			{
				if ((this._useMFICutoff != value))
				{
					this.OnuseMFICutoffChanging(value);
					this.SendPropertyChanging();
					this._useMFICutoff = value;
					this.SendPropertyChanged("useMFICutoff");
					this.OnuseMFICutoffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFICutoffValue", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> MFICutoffValue
		{
			get
			{
				return this._MFICutoffValue;
			}
			set
			{
				if ((this._MFICutoffValue != value))
				{
					this.OnMFICutoffValueChanging(value);
					this.SendPropertyChanging();
					this._MFICutoffValue = value;
					this.SendPropertyChanged("MFICutoffValue");
					this.OnMFICutoffValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID4DigitLogicID", DbType="Int")]
		public System.Nullable<int> ID4DigitLogicID
		{
			get
			{
				return this._ID4DigitLogicID;
			}
			set
			{
				if ((this._ID4DigitLogicID != value))
				{
					this.OnID4DigitLogicIDChanging(value);
					this.SendPropertyChanging();
					this._ID4DigitLogicID = value;
					this.SendPropertyChanged("ID4DigitLogicID");
					this.OnID4DigitLogicIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjAltCalc1", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> adjAltCalc1
		{
			get
			{
				return this._adjAltCalc1;
			}
			set
			{
				if ((this._adjAltCalc1 != value))
				{
					this.OnadjAltCalc1Changing(value);
					this.SendPropertyChanging();
					this._adjAltCalc1 = value;
					this.SendPropertyChanged("adjAltCalc1");
					this.OnadjAltCalc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjAltCalc2", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> adjAltCalc2
		{
			get
			{
				return this._adjAltCalc2;
			}
			set
			{
				if ((this._adjAltCalc2 != value))
				{
					this.OnadjAltCalc2Changing(value);
					this.SendPropertyChanging();
					this._adjAltCalc2 = value;
					this.SendPropertyChanged("adjAltCalc2");
					this.OnadjAltCalc2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TailLogicID", DbType="Int")]
		public System.Nullable<int> TailLogicID
		{
			get
			{
				return this._TailLogicID;
			}
			set
			{
				if ((this._TailLogicID != value))
				{
					this.OnTailLogicIDChanging(value);
					this.SendPropertyChanging();
					this._TailLogicID = value;
					this.SendPropertyChanged("TailLogicID");
					this.OnTailLogicIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_excludeweak", DbType="Int")]
		public System.Nullable<int> excludeweak
		{
			get
			{
				return this._excludeweak;
			}
			set
			{
				if ((this._excludeweak != value))
				{
					this.OnexcludeweakChanging(value);
					this.SendPropertyChanging();
					this._excludeweak = value;
					this.SendPropertyChanged("excludeweak");
					this.OnexcludeweakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int")]
		public System.Nullable<int> Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetSampleForLoadResult
	{
		
		private string _sessionID;
		
		private string _sampleID;
		
		private string _bead;
		
		private System.Nullable<decimal> _rawValue;
		
		private System.Nullable<decimal> _adjust1;
		
		private System.Nullable<decimal> _adjust2;
		
		private System.Nullable<decimal> _adjust3;
		
		private System.Nullable<decimal> _adjustN;
		
		private string _assignment;
		
		private System.Nullable<System.DateTime> _test_date;
		
		private System.Nullable<decimal> _hiBGAdjust1;
		
		private System.Nullable<decimal> _hiBGAdjust2;
		
		private System.Nullable<decimal> _hiBGAdjust3;
		
		private string _hiBGAssignment;
		
		private System.Nullable<decimal> _weakPct;
		
		private System.Nullable<int> _overRide;
		
		private System.Nullable<int> _beadCount;
		
		private System.Nullable<int> _score;
		
		private System.Nullable<int> _hiBGScore;
		
		private string _consensus;
		
		private System.Nullable<decimal> _ProgressBarValue;
		
		private int _Adj1ProgressBarValue;
		
		private int _Adj2ProgressBarValue;
		
		private int _Adj3ProgressBarValue;
		
		private int _AdjNProgressBarValue;
		
		private string _EpitopeCol;
		
		private string _AlleleA1Col;
		
		private string _AlleleA2Col;
		
		private string _AlleleB1Col;
		
		private string _AlleleB2Col;
		
		private string _AlleleBw4Col;
		
		private string _AlleleBw6Col;
		
		private string _AlleleC1Col;
		
		private string _AlleleC2Col;
		
		private string _AlleleDR1Col;
		
		private string _AlleleDR2Col;
		
		private string _AlleleDR5x1Col;
		
		private string _AlleleDR5x2Col;
		
		private string _AlleleDQB1Col;
		
		private string _AlleleDQB2Col;
		
		private System.Nullable<bool> _HighlightMe;
		
		private System.Nullable<bool> _IsDirty;
		
		private System.Nullable<decimal> _Con3;
		
		private string _AlleleDQA1Col;
		
		private string _AlleleDQA2Col;
		
		private string _AlleleDPB1Col;
		
		private string _AlleleDPB2Col;
		
		private string _DonorID;
		
		public GetSampleForLoadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sessionID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sessionID
		{
			get
			{
				return this._sessionID;
			}
			set
			{
				if ((this._sessionID != value))
				{
					this._sessionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sampleID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sampleID
		{
			get
			{
				return this._sampleID;
			}
			set
			{
				if ((this._sampleID != value))
				{
					this._sampleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bead", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string bead
		{
			get
			{
				return this._bead;
			}
			set
			{
				if ((this._bead != value))
				{
					this._bead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rawValue", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> rawValue
		{
			get
			{
				return this._rawValue;
			}
			set
			{
				if ((this._rawValue != value))
				{
					this._rawValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjust1", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> adjust1
		{
			get
			{
				return this._adjust1;
			}
			set
			{
				if ((this._adjust1 != value))
				{
					this._adjust1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjust2", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> adjust2
		{
			get
			{
				return this._adjust2;
			}
			set
			{
				if ((this._adjust2 != value))
				{
					this._adjust2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjust3", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> adjust3
		{
			get
			{
				return this._adjust3;
			}
			set
			{
				if ((this._adjust3 != value))
				{
					this._adjust3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjustN", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> adjustN
		{
			get
			{
				return this._adjustN;
			}
			set
			{
				if ((this._adjustN != value))
				{
					this._adjustN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignment", DbType="NVarChar(12)")]
		public string assignment
		{
			get
			{
				return this._assignment;
			}
			set
			{
				if ((this._assignment != value))
				{
					this._assignment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> test_date
		{
			get
			{
				return this._test_date;
			}
			set
			{
				if ((this._test_date != value))
				{
					this._test_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiBGAdjust1", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> hiBGAdjust1
		{
			get
			{
				return this._hiBGAdjust1;
			}
			set
			{
				if ((this._hiBGAdjust1 != value))
				{
					this._hiBGAdjust1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiBGAdjust2", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> hiBGAdjust2
		{
			get
			{
				return this._hiBGAdjust2;
			}
			set
			{
				if ((this._hiBGAdjust2 != value))
				{
					this._hiBGAdjust2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiBGAdjust3", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> hiBGAdjust3
		{
			get
			{
				return this._hiBGAdjust3;
			}
			set
			{
				if ((this._hiBGAdjust3 != value))
				{
					this._hiBGAdjust3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiBGAssignment", DbType="NVarChar(12)")]
		public string hiBGAssignment
		{
			get
			{
				return this._hiBGAssignment;
			}
			set
			{
				if ((this._hiBGAssignment != value))
				{
					this._hiBGAssignment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weakPct", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> weakPct
		{
			get
			{
				return this._weakPct;
			}
			set
			{
				if ((this._weakPct != value))
				{
					this._weakPct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overRide", DbType="Int")]
		public System.Nullable<int> overRide
		{
			get
			{
				return this._overRide;
			}
			set
			{
				if ((this._overRide != value))
				{
					this._overRide = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beadCount", DbType="Int")]
		public System.Nullable<int> beadCount
		{
			get
			{
				return this._beadCount;
			}
			set
			{
				if ((this._beadCount != value))
				{
					this._beadCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score", DbType="Int")]
		public System.Nullable<int> score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this._score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiBGScore", DbType="Int")]
		public System.Nullable<int> hiBGScore
		{
			get
			{
				return this._hiBGScore;
			}
			set
			{
				if ((this._hiBGScore != value))
				{
					this._hiBGScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consensus", DbType="Char(2)")]
		public string consensus
		{
			get
			{
				return this._consensus;
			}
			set
			{
				if ((this._consensus != value))
				{
					this._consensus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgressBarValue", DbType="Decimal(35,19)")]
		public System.Nullable<decimal> ProgressBarValue
		{
			get
			{
				return this._ProgressBarValue;
			}
			set
			{
				if ((this._ProgressBarValue != value))
				{
					this._ProgressBarValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adj1ProgressBarValue", DbType="Int NOT NULL")]
		public int Adj1ProgressBarValue
		{
			get
			{
				return this._Adj1ProgressBarValue;
			}
			set
			{
				if ((this._Adj1ProgressBarValue != value))
				{
					this._Adj1ProgressBarValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adj2ProgressBarValue", DbType="Int NOT NULL")]
		public int Adj2ProgressBarValue
		{
			get
			{
				return this._Adj2ProgressBarValue;
			}
			set
			{
				if ((this._Adj2ProgressBarValue != value))
				{
					this._Adj2ProgressBarValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adj3ProgressBarValue", DbType="Int NOT NULL")]
		public int Adj3ProgressBarValue
		{
			get
			{
				return this._Adj3ProgressBarValue;
			}
			set
			{
				if ((this._Adj3ProgressBarValue != value))
				{
					this._Adj3ProgressBarValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjNProgressBarValue", DbType="Int NOT NULL")]
		public int AdjNProgressBarValue
		{
			get
			{
				return this._AdjNProgressBarValue;
			}
			set
			{
				if ((this._AdjNProgressBarValue != value))
				{
					this._AdjNProgressBarValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EpitopeCol", DbType="VarChar(4000)")]
		public string EpitopeCol
		{
			get
			{
				return this._EpitopeCol;
			}
			set
			{
				if ((this._EpitopeCol != value))
				{
					this._EpitopeCol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleA1Col", DbType="VarChar(30)")]
		public string AlleleA1Col
		{
			get
			{
				return this._AlleleA1Col;
			}
			set
			{
				if ((this._AlleleA1Col != value))
				{
					this._AlleleA1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleA2Col", DbType="VarChar(30)")]
		public string AlleleA2Col
		{
			get
			{
				return this._AlleleA2Col;
			}
			set
			{
				if ((this._AlleleA2Col != value))
				{
					this._AlleleA2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleB1Col", DbType="VarChar(30)")]
		public string AlleleB1Col
		{
			get
			{
				return this._AlleleB1Col;
			}
			set
			{
				if ((this._AlleleB1Col != value))
				{
					this._AlleleB1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleB2Col", DbType="VarChar(30)")]
		public string AlleleB2Col
		{
			get
			{
				return this._AlleleB2Col;
			}
			set
			{
				if ((this._AlleleB2Col != value))
				{
					this._AlleleB2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleBw4Col", DbType="VarChar(30)")]
		public string AlleleBw4Col
		{
			get
			{
				return this._AlleleBw4Col;
			}
			set
			{
				if ((this._AlleleBw4Col != value))
				{
					this._AlleleBw4Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleBw6Col", DbType="VarChar(30)")]
		public string AlleleBw6Col
		{
			get
			{
				return this._AlleleBw6Col;
			}
			set
			{
				if ((this._AlleleBw6Col != value))
				{
					this._AlleleBw6Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleC1Col", DbType="VarChar(30)")]
		public string AlleleC1Col
		{
			get
			{
				return this._AlleleC1Col;
			}
			set
			{
				if ((this._AlleleC1Col != value))
				{
					this._AlleleC1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleC2Col", DbType="VarChar(30)")]
		public string AlleleC2Col
		{
			get
			{
				return this._AlleleC2Col;
			}
			set
			{
				if ((this._AlleleC2Col != value))
				{
					this._AlleleC2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDR1Col", DbType="VarChar(30)")]
		public string AlleleDR1Col
		{
			get
			{
				return this._AlleleDR1Col;
			}
			set
			{
				if ((this._AlleleDR1Col != value))
				{
					this._AlleleDR1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDR2Col", DbType="VarChar(30)")]
		public string AlleleDR2Col
		{
			get
			{
				return this._AlleleDR2Col;
			}
			set
			{
				if ((this._AlleleDR2Col != value))
				{
					this._AlleleDR2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDR5x1Col", DbType="VarChar(30)")]
		public string AlleleDR5x1Col
		{
			get
			{
				return this._AlleleDR5x1Col;
			}
			set
			{
				if ((this._AlleleDR5x1Col != value))
				{
					this._AlleleDR5x1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDR5x2Col", DbType="VarChar(30)")]
		public string AlleleDR5x2Col
		{
			get
			{
				return this._AlleleDR5x2Col;
			}
			set
			{
				if ((this._AlleleDR5x2Col != value))
				{
					this._AlleleDR5x2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDQB1Col", DbType="VarChar(30)")]
		public string AlleleDQB1Col
		{
			get
			{
				return this._AlleleDQB1Col;
			}
			set
			{
				if ((this._AlleleDQB1Col != value))
				{
					this._AlleleDQB1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDQB2Col", DbType="VarChar(30)")]
		public string AlleleDQB2Col
		{
			get
			{
				return this._AlleleDQB2Col;
			}
			set
			{
				if ((this._AlleleDQB2Col != value))
				{
					this._AlleleDQB2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighlightMe", DbType="Bit")]
		public System.Nullable<bool> HighlightMe
		{
			get
			{
				return this._HighlightMe;
			}
			set
			{
				if ((this._HighlightMe != value))
				{
					this._HighlightMe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDirty", DbType="Bit")]
		public System.Nullable<bool> IsDirty
		{
			get
			{
				return this._IsDirty;
			}
			set
			{
				if ((this._IsDirty != value))
				{
					this._IsDirty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con3", DbType="Decimal(12,4)")]
		public System.Nullable<decimal> Con3
		{
			get
			{
				return this._Con3;
			}
			set
			{
				if ((this._Con3 != value))
				{
					this._Con3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDQA1Col", DbType="VarChar(30)")]
		public string AlleleDQA1Col
		{
			get
			{
				return this._AlleleDQA1Col;
			}
			set
			{
				if ((this._AlleleDQA1Col != value))
				{
					this._AlleleDQA1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDQA2Col", DbType="VarChar(30)")]
		public string AlleleDQA2Col
		{
			get
			{
				return this._AlleleDQA2Col;
			}
			set
			{
				if ((this._AlleleDQA2Col != value))
				{
					this._AlleleDQA2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDPB1Col", DbType="VarChar(30)")]
		public string AlleleDPB1Col
		{
			get
			{
				return this._AlleleDPB1Col;
			}
			set
			{
				if ((this._AlleleDPB1Col != value))
				{
					this._AlleleDPB1Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleleDPB2Col", DbType="VarChar(30)")]
		public string AlleleDPB2Col
		{
			get
			{
				return this._AlleleDPB2Col;
			}
			set
			{
				if ((this._AlleleDPB2Col != value))
				{
					this._AlleleDPB2Col = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonorID", DbType="VarChar(30)")]
		public string DonorID
		{
			get
			{
				return this._DonorID;
			}
			set
			{
				if ((this._DonorID != value))
				{
					this._DonorID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
